apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-q7bn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0044-tenant/ci1t-830-0044-app/devfile-sample-q7bn@sha256:dc93caf0509265969c06c03263a862ab58ea5a3b6e74c8c1ba83a451cdc8af66
        name: my-nodejs
        resources: {}
status: {}
